version: '3.8'

services:
  eventnotifier:
    build: .
    container_name: event-notifier
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped